name: swagger-ui
kind: pipeline
type: kubernetes

#globals:
#  - &regsitry_creds
#    REGISTRY_USERNAME:
#      from_secret: registry_username
#    REGISTRY_PASSWORD:
#      from_secret: registry_password
#    REGISTRY_URL:
#      from_secret: registry_url

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: harbor.adamkoro.com/library/swagger-ui
    tags: latest
