name: swagger-ui
kind: pipeline
type: kubernetes

steps:
- name: build and push container image
  image: plugins/kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: adamkoro/go-swagger-ui
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}

- name: Change image tag in k8s yaml
  image: harbor.adamkoro.com/bci/bci-base:15.4
  environment:
    FILE: swagger-ui.yaml
  commands:
  - zypper ref && zypper in -y yq
  - yq -i '.spec.template.spec.containers[0].image = "adamkoro/go-swagger-ui:${DRONE_COMMIT_SHA:0:7}"' k8s/deployment.yaml

- name: push to git
  image: appleboy/drone-git-push
  settings:
    branch: main
    remote: git@github.com:adamkoro/go-swagger-ui.git
    force: false
    commit: true
    commit_message: "Update by Drone CI - image tag update"
    author_name:
      from_secret: github_username
    author_email:
      from_secret: github_email
    ssh_key:
      from_secret: github_private_ssh_key


trigger:
  event:
  - push
  branch:
  - master

