name: swagger-ui
kind: pipeline
type: kubernetes

steps:
- name: build-binary
  image: harbor.adamkoro.com/bci/golang:1.19
  commands:
  - cd swagger-ui
  - go build -ldflags="-s -w" -o /build/swagger-ui
  volumes:
  - name: tmp-build
    path: /build

- name: build-image
  image: plugins/kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: adamkoro/go-swagger-ui
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}
    registry: docker.io
  volumes:
  - name: tmp-build
    path: /build

volumes:
- name: tmp-build
  temp: {}