name: swagger-ui
kind: pipeline
type: kubernetes

steps:
- name: build-image
  image: plugins/kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: adamkoro/go-swagger-ui
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}
  volumes:
  - name: tmp-build
    path: /build