name: swagger-ui
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: generate password
    image: registry.suse.com/bci/bci-base:15.5
    commands:
      - echo "TF_VAR_linode_root_pass=$(openssl rand -base64 32 | tr -d '\n' | base64 -w 0)" > /build_env/linode_root_pass
    volumes:
      - name: build_env
        path: /build_env

  - name: clone setup repo
    image: registry.suse.com/bci/bci-base:15.5
    commands:
      - zypper ref && zypper -n in git
      - git clone https://github.com/adamkoro/linode_terraform.git /build_env/setup
    volumes:
      - name: build_env
        path: /build_env

  - name: create linode
    image: registry.adamkoro.com/docker/hashicorp/terraform:1.5.5
    environment:
      TF_VAR_linode_token:
        from_secret: linode_token
      TF_VAR_linode_authorized_keys:
        from_secret: linode_authorized_keys
      TF_VAR_linode_label: swagger-ui-build
    commands:
      - export $(cat /build_env/linode_root_pass | xargs)
      - cd /build_env/setup
      - terraform -chdir=terraform/ init 
      - terraform -chdir=terraform/ plan
      - terraform -chdir=terraform/ apply -auto-approve
    volumes:
      - name: build_env
        path: /build_env
    when:
      status:
        - success

  - name: wait for linode
    image: registry.adamkoro.com/library/ansible:latest
    environment:
      ANSIBLE_USER: root
    commands:
      - while ! nc -q0 $(cat /build_env/linode_ip_address | cut -d'=' -f2) 22 < /dev/null > /dev/null 2>&1; do sleep 1;done
    volumes:
      - name: build_env
        path: /build_env
    when:
      status:
        - success

  - name: setup linode
    image: registry.adamkoro.com/library/ansible:latest
    environment:
      ANSIBLE_USER: root
    commands:
      - cd /build_env/setup
      - ansible-galaxy collection install community.docker
      - ansible-playbook ansible/docker_setup.yml -i $(cat /build_env/linode_ip_address | cut -d'=' -f2), --extra-vars "ansible_password=$(cat /build_env/linode_root_pass | cut -d'=' -f2)"
    volumes:
      - name: build_env
        path: /build_env
    when:
      status:
        - success

  - name: delete linode
    image: registry.adamkoro.com/docker/hashicorp/terraform:1.5.5
    environment:
      TF_VAR_linode_token:
        from_secret: linode_token
      TF_VAR_linode_authorized_keys:
        from_secret: linode_authorized_keys
    commands:
      - export $(cat /build_env/linode_root_pass | xargs)
      - cd /build_env/setup
      - terraform -chdir=terraform/ init 
      - terraform -chdir=terraform/ destroy -auto-approve
    volumes:
      - name: build_env
        path: /build_env
    when:
      status:
        - failure
        - success


volumes:
  #- name: dockersock
  #  temp: {}
  - name: build_env
    temp: {}

node:
  type: hosted-amd64