name: swagger-ui
kind: pipeline
type: kubernetes

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: harbor.adamkoro.com/swagger-ui/swagger-ui
    registry: harbor.adamkoro.com
    tags: 
      - latest
