name: swagger-ui
kind: pipeline
type: kubernetes

steps:
- name: build-binary
  image: harbor.adamkoro.com/bci/golang:1.19
  commands:
  - cd swagger-ui
  - go build -ldflags="-s -w" -o /build/swagger-ui
  volumes:
  - name: tmp-build
    path: /build

- name: build
  image: plugins/buildah
  settings:
    registry: harbor.adamkoro.com
    repo: harbor.adamkoro.com/swagger-ui/swagger-ui
    dockerfile: Dockerfile
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    tags:
    - latest
    layers: true

  volumes:
  - name: tmp-build
    path: /build

volumes:
- name: tmp-build
  temp: {}