name: swagger-ui
kind: pipeline
type: kubernetes

steps:
- name: create-registry-auth
  image: harbor.adamkoro.com/bci/bci-micro:15.4
  commands:
  - echo "{\"auths\":{\"harbor.adamkoro.com\":{\"auth\":\"$(echo "${registry_username}:${registry_password}" | base64)\"}}}" > /kaniko/.docker/config.json
  volumes:
  - name: kaniko-auth
    path: /kaniko/.docker

- name: build-binary
  image: harbor.adamkoro.com/bci/golang:1.19
  commands:
  - cd swagger-ui
  - go build -ldflags="-s -w" -o /build/swagger-ui
  volumes:
  - name: tmp-build
    path: /build

- name: build
  image: harbor.adamkoro.com/library/kaniko-executer@sha256:08a12f45e82f6221db6750eef29599dc6bcc18c24805a2204fff37f3ab78d39f
  commands:
  - /usr/bin/executor --dockerfile=Dockerfile --context=dir:///build --destination=harbor.adamkoro.com/swagger-ui/swagger-ui:latest
  volumes:
  - name: kaniko-auth
    path: /kaniko/.docker

volumes:
- name: kaniko-auth
  temp: {}