name: swagger-ui
kind: pipeline
type: kubernetes

steps:
#- name: create-registry-auth
#  image: harbor.adamkoro.com/bci/bci-micro:15.4
#  commands:
#  - echo "{\"auths\":{\"https://harbor.adamkoro.com\":{\"auth\":\"$(echo -n "${registry_username}:${registry_password}" | base64)\"}}}" > /kaniko/.docker/config.json
#  - cat /kaniko/.docker/config.json
#  volumes:
#  - name: kaniko-auth
#    path: /kaniko/.docker

- name: build-binary
  image: harbor.adamkoro.com/bci/golang:1.19
  commands:
  - cd swagger-ui
  - go build -ldflags="-s -w" -o /build/swagger-ui
  volumes:
  - name: tmp-build
    path: /build

- name: build-image
  image: harbor.adamkoro.com/library/kaniko-executer@sha256:08a12f45e82f6221db6750eef29599dc6bcc18c24805a2204fff37f3ab78d39f
  environment:
    DOCKER_CONFIG: "eyJhdXRocyI6eyJoYXJib3IuYWRhbWtvcm8uY29tIjp7InVzZXJuYW1lIjoicm9ib3QrZnVsbCIsInBhc3N3b3JkIjoiNEtLdnNTTVJGNTJxcGdqQnNaS2dBYWtvUmlPc1d2Q3IifX19"
  commands:
  - mkdir -p /kaniko/.docker
  - echo "$DOCKER_CONFIG" | base64 -d > /kaniko/.docker/config.json
  - echo "$DOCKER_CONFIG"
  - cat /kaniko/.docker/config.json
  - /usr/bin/kaniko --dockerfile=Dockerfile --context=dir:///build --destination=harbor.adamkoro.com/swagger-ui/swagger-ui:latest
  volumes:
  - name: tmp-build
    path: /build

volumes:
- name: tmp-build
  temp: {}
---
kind: secret
name: harbor-auth 
get:
  path: harborcred
  name: .dockerconfigjson