name: swagger-ui
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/

steps:
- name: wait for docker service
  image: docker:dind
  volumes:
    - name: dockersock
      path: /var/run/
  commands:
  - while docker info -f '{{.ServerVersion}}'; do sleep 1; done


- name: build image
  image: docker:dind
  environment:
    REGISTRY_USER:
      from_secret: registry_user
    REGISTRY_PASSWORD:
      from_secret: registry_password
  volumes:
    - name: dockersock
      path: /var/run/
  commands:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.adamkoro.com
  - docker buildx create --use --name mybuilder
  - docker buildx build --platform linux/amd64,linux/arm64 -t registry.adamkoro.com/library/go-swagger-ui:${DRONE_COMMIT_SHA:0:7} -t registry.adamkoro.com/library/go-swagger-ui:latest . --push -f Dockerfile


#- name: change image tag
#  image: harbor.adamkoro.com/bci/bci-base:15.4
#  commands:
#  - zypper ar http://download.opensuse.org/distribution/leap/15.4/repo/oss/ leap_15.4 && zypper -n --gpg-auto-import-keys ref && zypper -n in yq
#  - yq -i '.spec.template.spec.containers[0].image = "adamkoro/go-swagger-ui:${DRONE_COMMIT_SHA:0:7}"' k8s/deployment.yaml
#
#- name: push to repo
#  image: appleboy/drone-git-push
#  settings:
#    branch: main
#    remote: git@github.com:adamkoro/go-swagger-ui.git
#    force: false
#    commit: true
#    commit_message: "Update by Drone CI - image tag update"
#    author_name:
#      from_secret: github_username
#    author_email:
#      from_secret: github_email
#    ssh_key:
#      from_secret: github_private_ssh_key
#
volumes:
  - name: dockersock
    temp: {}

node:
  type: hosted-amd64