name: swagger-ui
kind: pipeline
type: kubernetes

steps:
#- name: prebuild
#  image: harbor.adamkoro.com/bci/bci-base:15.4
#  commands:
#  - echo "{\"auths\":{\"harbor.adamkoro.com\":{\"auth\":\"$(echo "${registry_username}:${registry_password}" | base64)\"}}}" > /kaniko/.docker/config.json
#  volumes:
#  - name: registry-auth
#    path: /kaniko/.docker

- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: harbor.adamkoro.com/swagger-ui/swagger-ui
    tags:
    - latest
    registry: harbor.adamkoro.com
    dockerfile: Dockerfile

#volumes:
#- name: registry-auth
#  temp: {}